# Generated by Django 6.0.4 on 2026-04-23 18:50

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_excel', models.FileField(upload_to=jobs.models.excel_upload_to)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('preview', 'Prévia'), ('queued', 'Na fila'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='draft', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('zip_file', models.FileField(blank=True, upload_to=jobs.models.job_zip_upload_to)),
                ('last_error', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='editor.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('output_pdf', models.FileField(blank=True, upload_to=jobs.models.item_pdf_upload_to)),
                ('error_message', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.generationjob')),
            ],
            options={
                'ordering': ['row_number'],
                'unique_together': {('job', 'row_number')},
            },
        ),
    ]
