# Generated by Django 6.0.4 on 2026-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('preview', 'Amostra'), ('full', 'Lote completo')], default='preview', max_length=20),
        ),
    ]
