# Generated by Django 6.0.4 on 2026-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_generationjob_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
