# Generated by Django 6.0.8 on 2026-08-22 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_generationjob_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generationitem",
            options={
                "ordering": ["row_number"],
                "verbose_name": "item do lote",
                "verbose_name_plural": "itens do lote",
            },
        ),
        migrations.AlterModelOptions(
            name="generationjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "lote",
                "verbose_name_plural": "lotes",
            },
        ),
    ]
