# Generated by Django 6.0.8 on 2026-08-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_alter_generationitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationitem",
            name="display_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
