# Generated by Django 6.0.4 on 2026-07-25 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('termos', 'Termos de Uso'), ('privacidade', 'Política de Privacidade')], max_length=20, verbose_name='tipo')),
                ('versao', models.CharField(max_length=20, verbose_name='versão')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='situação')),
                ('corpo_md', models.TextField(help_text='Escreva em Markdown. O HTML é gerado e sanitizado na publicação.', verbose_name='texto (Markdown)')),
                ('corpo_html', models.TextField(blank=True, editable=False, verbose_name='HTML publicado')),
                ('sha256', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='sha256')),
                ('material', models.BooleanField(default=True, help_text='Marcado, obriga todos os usuários a aceitarem de novo. Desmarque apenas para correções de redação que não alterem direitos e obrigações.', verbose_name='mudança material')),
                ('vigente_desde', models.DateTimeField(blank=True, null=True, verbose_name='vigente desde')),
                ('publicado_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publicado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'documento legal',
                'verbose_name_plural': 'documentos legais',
                'ordering': ['tipo', '-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'versao'), name='legal_documento_tipo_versao')],
            },
        ),
        migrations.CreateModel(
            name='AceiteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_label', models.CharField(blank=True, help_text='Congelado no momento do aceite; sobrevive à exclusão da conta.', max_length=200, verbose_name='identificação do usuário')),
                ('e_visitante', models.BooleanField(default=False, verbose_name='era visitante')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='sessão')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='navegador')),
                ('aceito_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='aceito em')),
                ('origem', models.CharField(choices=[('cadastro', 'Cadastro'), ('visitante', 'Entrada como visitante'), ('reaceite', 'Re-aceite de nova versão'), ('upload_anonimo', 'Uso anônimo')], max_length=20, verbose_name='origem')),
                ('documento_sha256', models.CharField(max_length=64, verbose_name='sha256 do texto aceito')),
                ('evidencia', models.JSONField(blank=True, default=dict, verbose_name='evidência')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceites_legais', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='legal.documentolegal', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'aceite',
                'verbose_name_plural': 'aceites',
                'ordering': ['-aceito_em'],
                'indexes': [models.Index(fields=['documento', 'usuario'], name='legal_aceit_documen_994669_idx'), models.Index(fields=['-aceito_em'], name='legal_aceit_aceito__176336_idx')],
            },
        ),
    ]
