# Generated by Django 6.0.4 on 2026-04-23 18:50

import django.db.models.deletion
import editor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fonts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_pdf', models.FileField(upload_to=editor.models.background_upload_to)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('page_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('page_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('editor_state', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
                'unique_together': {('user', 'slug', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('excel_column', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('x', models.DecimalField(decimal_places=2, max_digits=8)),
                ('y', models.DecimalField(decimal_places=2, max_digits=8)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('font_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_bold', models.BooleanField(default=False)),
                ('is_italic', models.BooleanField(default=False)),
                ('text_align', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('letter_spacing', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('line_height', models.DecimalField(decimal_places=2, default=1.2, max_digits=6)),
                ('max_lines', models.PositiveIntegerField(default=1)),
                ('overflow_mode', models.CharField(choices=[('truncate', 'Cortar'), ('wrap', 'Quebrar linha'), ('shrink', 'Reduzir fonte'), ('error', 'Gerar erro')], default='truncate', max_length=20)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_fields', to='fonts.fontasset')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='editor.documenttemplate')),
            ],
            options={
                'ordering': ['page_number', 'order_index', 'id'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
