# Generated by Django 6.0.4 on 2026-04-23 19:03

import editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to=editor.models.preview_upload_to),
        ),
    ]
