# Generated by Django 6.0.4 on 2026-04-23 19:08

import django.db.models.deletion
import editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_documenttemplate_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePreviewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=editor.models.preview_page_upload_to)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_pages', to='editor.documenttemplate')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('template', 'page_number')},
            },
        ),
    ]
