# Generated by Django 6.0.4 on 2026-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_templatepreviewpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='empty_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='integer_keep_sign',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='integer_min_digits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='suffix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='text_transform',
            field=models.CharField(choices=[('none', 'Sem transformação'), ('lower', 'Minúsculas'), ('upper', 'Maiúsculas'), ('title', 'Iniciais maiúsculas'), ('title_smart', 'Palavras principais')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='transform_exceptions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='trim_whitespace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='value_type',
            field=models.CharField(choices=[('text', 'Texto'), ('integer', 'Inteiro')], default='text', max_length=20),
        ),
    ]
