# Generated by Django 6.0.4 on 2026-04-23 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_templatefield_empty_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('user', 'slug')},
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='is_bold',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='is_italic',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='letter_spacing',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='preview_text',
        ),
        migrations.RemoveField(
            model_name='templatefield',
            name='suffix',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='version',
        ),
    ]
