# Generated by Django 6.0.4 on 2026-04-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_alter_documenttemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='border_blur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='border_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='border_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='border_opacity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='border_size_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
