# Generated by Django 6.0.4 on 2026-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_templatefield_border_blur_templatefield_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='rotation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
