# Generated by Django 6.0.8 on 2026-08-22 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0007_templatefield_rotation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttemplate",
            options={
                "ordering": ["name", "-updated_at"],
                "verbose_name": "projeto",
                "verbose_name_plural": "projetos",
            },
        ),
        migrations.AlterModelOptions(
            name="templatefield",
            options={
                "ordering": ["page_number", "order_index", "id"],
                "verbose_name": "campo",
                "verbose_name_plural": "campos",
            },
        ),
        migrations.AlterModelOptions(
            name="templatepreviewpage",
            options={
                "ordering": ["page_number"],
                "verbose_name": "página de pré-visualização",
                "verbose_name_plural": "páginas de pré-visualização",
            },
        ),
    ]
