# Generated by Django 6.0.8 on 2026-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0008_alter_documenttemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="filename_pattern",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="grow_direction",
            field=models.CharField(
                choices=[("down", "Para baixo"), ("up", "Para cima")], default="down", max_length=10
            ),
        ),
    ]
