# Generated by Django 6.0.8 on 2026-08-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0009_documenttemplate_filename_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttemplate",
            name="filename_space_mode",
            field=models.CharField(
                choices=[
                    ("keep", "Manter como estão no texto"),
                    ("strip", "Remover"),
                    ("replace", "Substituir por"),
                ],
                default="keep",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="filename_space_replacement",
            field=models.CharField(blank=True, default="-", max_length=5),
        ),
    ]
