# Generated by Django 6.0.8 on 2026-08-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editor", "0010_documenttemplate_filename_space_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="text_strikethrough",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="templatefield",
            name="text_underline",
            field=models.BooleanField(default=False),
        ),
    ]
