# Generated by Django 6.0.8 on 2026-08-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_templatefield_text_strikethrough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='transform_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
