# Generated by Django 6.0.8 on 2026-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_templatefield_transform_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='filename_case',
            field=models.CharField(choices=[('none', 'Sem transformação'), ('upper', 'Maiúsculas'), ('lower', 'Minúsculas')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='filename_case_columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='filename_strip_accents',
            field=models.BooleanField(default=False),
        ),
    ]
