# Generated by Django 6.0.8 on 2026-08-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_documenttemplate_filename_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='lock_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='vertical_align',
            field=models.CharField(choices=[('top', 'Topo'), ('middle', 'Meio'), ('bottom', 'Base')], default='top', max_length=10),
        ),
    ]
