# Generated by Django 6.0.8 on 2026-09-01 22:04

import editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_templatefield_lock_size_templatefield_vertical_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='source_excel',
            field=models.FileField(blank=True, upload_to=editor.models.excel_upload_to),
        ),
    ]
