# Generated by Django 6.0.4 on 2026-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fontasset',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
