# Generated by Django 6.0.8 on 2026-08-22 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fonts", "0002_fontasset_is_builtin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fontasset",
            options={
                "ordering": ["family", "variant", "name"],
                "verbose_name": "fonte",
                "verbose_name_plural": "fontes",
            },
        ),
    ]
