# Generated by Django 6.0.8 on 2026-08-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fonts", "0003_alter_fontasset_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fontasset",
            options={
                "ordering": ["family", "weight", "is_italic", "name"],
                "verbose_name": "fonte",
                "verbose_name_plural": "fontes",
            },
        ),
        migrations.AddField(
            model_name="fontasset",
            name="is_italic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fontasset",
            name="weight",
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name="fontasset",
            name="variant",
            field=models.CharField(default="Regular", max_length=40),
        ),
    ]
